### ISSUE TITLE
[cuda][windows] error C4703: potentially uninitialized local pointer variable 'Event' used"

### ISSUE THREAD

**Issue by ashadrina** [oneapi-src/unified-runtime#2497]
Build with MSVC  fails with an error message "source\adapters\cuda\device.cpp(1257): error C4703: potentially uninitialized local pointer variable 'Event' used". https://github.com/oneapi-src/unified-runtime/blob/76a96238d911500294c709efbb10d0a6661244f6/source/adapters/cuda/device.cpp#L1242C3-L1242C11

It started failing after https://github.com/oneapi-src/unified-runtime/commit/5bc8c9250f6f21cd50e9e58fa8ac54e5bdf0007b which removes default initializer for CUEvent.

Here was the correct initialization:
https://github.com/oneapi-src/unified-runtime/commit/8e5634775bcf6e8bb9067a1aa5564605fb5bd043#diff-641b75ae8137280ac68523353cbb6eb8059f8581b35261d7a96d179a478229bcL1238

**Comment by kbenzie** [comment]
This warning is introduced by `/W4` but the commit https://github.com/oneapi-src/unified-runtime/commit/5bc8c9250f6f21cd50e9e58fa8ac54e5bdf0007b also reverted the introduction of `/W4` and changed back to `/W3`.

Are you setting the `/W4` flag in your build?

**Comment by ashadrina** [comment]
Hi @kbenzie, thank you for looking into this issue. I am building the intel\llvm compiler with CUDA backend support, so no, I am not changing any of the UR configs. It is downloaded and compiled automatically. You can try reproducing the issue with 2024-12-16, 2024-12-18, 2024-12-19 builds , for example, https://github.com/intel/llvm/tree/nightly-2024-12-19

**Comment by kbenzie** [comment]
This would have also failed before the reverted change which only existing on UR main branch for a short time.
